import { addMonths,format,startOfMonth } from 'date-fns'
import { ArrowDownRight,ArrowUpRight,CalendarClock,CreditCard,Plus,ReceiptText,WalletCards } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Cell,Pie,PieChart,ResponsiveContainer,Tooltip } from 'recharts'
import { Card,EmptyState,PageHeader } from '../components/ui'
import { useData } from '../context/DataContext'
import { money,monthKey,monthLabel,shortDate } from '../utils/format'
import { expensesForPeriod } from '../utils/finance'
export default function DashboardPage(){const data=useData(),navigate=useNavigate(),current=monthKey(),previous=monthKey(addMonths(new Date(),-1));const monthTx=expensesForPeriod(data,current),spent=monthTx.reduce((s,t)=>s+Number(t.amount),0),prev=expensesForPeriod(data,previous).reduce((s,t)=>s+Number(t.amount),0);const pending=data.installments.filter(i=>i.status==='pending'&&i.statement_period===current).reduce((s,i)=>s+Number(i.amount),0)+data.scheduled_payments.filter(p=>p.status==='pending'&&p.due_date?.startsWith(current)).reduce((s,p)=>s+Number(p.amount),0);const future=data.installments.filter(i=>i.status==='pending'&&i.statement_period>current).reduce((s,i)=>s+Number(i.amount),0);const upcoming=data.scheduled_payments.filter(p=>p.status!=='paid'&&p.due_date>=format(new Date(),'yyyy-MM-dd')).reduce((s,p)=>s+Number(p.amount),0);const byCat=data.categories.map(c=>({name:c.name,value:monthTx.filter(t=>t.category_id===c.id).reduce((s,t)=>s+Number(t.amount),0),color:c.color})).filter(x=>x.value>0);const change=prev?((spent-prev)/prev)*100:0;const nextCard=[...data.credit_cards].filter(c=>c.active).sort((a,b)=>a.closing_day-b.closing_day)[0]
 return <><PageHeader eyebrow={monthLabel()} title="Tu panorama financiero" description="Lo importante de este mes, sin ruido." action={<button className="button button--primary" onClick={()=>navigate('/agregar')}><Plus/>Registrar gasto</button>}/><div className="metrics-grid"><Metric icon={ReceiptText} label="Gastado este mes" value={money(spent)} meta={prev?`${Math.abs(change).toFixed(0)}% vs. mes anterior`:'Sin comparación anterior'} trend={change}/><Metric icon={WalletCards} label="Pendiente de pago" value={money(pending)} meta="Cuotas y resumen actual"/><Metric icon={CalendarClock} label="Próximos vencimientos" value={money(upcoming)} meta="Pagos programados"/><Metric icon={CreditCard} label="Comprometido a futuro" value={money(future)} meta="Cuotas de próximos meses"/></div><div className="dashboard-grid"><Card className="chart-card"><div className="card-heading"><div><span className="eyebrow">Distribución</span><h2>Gastos por categoría</h2></div></div>{byCat.length?<><div className="donut"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={byCat} dataKey="value" innerRadius={68} outerRadius={94} paddingAngle={3}>{byCat.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer><div><strong>{money(spent)}</strong><span>Total del mes</span></div></div><div className="legend">{byCat.slice(0,5).map(x=><span key={x.name}><i style={{background:x.color}}/>{x.name}<strong>{money(x.value)}</strong></span>)}</div></>:<EmptyState icon={ReceiptText} title="Todavía no hay gastos" text="Registrá tu primer consumo para ver la distribución."/>}</Card><Card><div className="card-heading"><div><span className="eyebrow">Actividad reciente</span><h2>Últimos consumos</h2></div><button className="text-button" onClick={()=>navigate('/movimientos')}>Ver todos</button></div><div className="transaction-list">{data.transactions.slice(0,6).map(t=><div className="transaction-row" key={t.id}><span className="transaction-icon" style={{background:data.categories.find(c=>c.id===t.category_id)?.color||'#94a3b8'}}><ReceiptText/></span><div><strong>{t.description}</strong><small>{t.merchant||data.categories.find(c=>c.id===t.category_id)?.name||'Sin categoría'} · {shortDate(t.purchase_date)}</small></div><strong>{money(t.amount,t.currency)}</strong></div>)}{!data.transactions.length&&<EmptyState icon={ReceiptText} title="Sin movimientos" text="Tus últimos consumos aparecerán acá."/>}</div></Card></div><div className="compact-grid"><Card><span className="eyebrow">Próximo cierre</span><h3>{nextCard?.name||'Sin tarjetas activas'}</h3><p>{nextCard?`Día ${nextCard.closing_day} de cada mes`:'Agregá una tarjeta para calcular cierres.'}</p></Card><Card><span className="eyebrow">Mes anterior</span><h3>{money(prev)}</h3><p>Gastos registrados desde {format(startOfMonth(addMonths(new Date(),-1)),'dd/MM')}.</p></Card></div></>}
function Metric({icon:Icon,label,value,meta,trend}){return <Card className="metric"><div className="metric-icon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{trend!==undefined&&trend!==0?(trend>0?<ArrowUpRight/>:<ArrowDownRight/>):null}{meta}</small></Card>}
