import { useState } from 'react'
import { addMonths } from 'date-fns'
import { Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
import { Card,PageHeader } from '../components/ui'
import { PAYMENT_METHODS } from '../constants/app'
import { useData } from '../context/DataContext'
import { money,monthKey } from '../utils/format'
import { expensesForPeriod } from '../utils/finance'
export default function ReportsPage(){const data=useData(),[month,setMonth]=useState(monthKey());const rows=expensesForPeriod(data,month),total=rows.reduce((s,t)=>s+Number(t.amount),0),byCat=data.categories.map(c=>({name:c.name,total:rows.filter(t=>t.category_id===c.id).reduce((s,t)=>s+Number(t.amount),0),color:c.color})).filter(x=>x.total),byMethod=PAYMENT_METHODS.map(([key,name])=>({name,total:rows.filter(t=>t.payment_method===key).reduce((s,t)=>s+Number(t.amount),0)})).filter(x=>x.total),evolution=Array.from({length:6},(_,i)=>{const key=monthKey(addMonths(new Date(),i-5));return{month:key.slice(5),total:expensesForPeriod(data,key).reduce((s,t)=>s+Number(t.amount),0)}});return <><PageHeader eyebrow="Análisis" title="Informes mensuales" description="Entendé tendencias y detectá dónde crecen tus gastos." action={<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>}/><div className="metrics-grid"><Card className="metric"><span>Total gastado</span><strong>{money(total)}</strong><small>{rows.length} movimientos y cuotas</small></Card><Card className="metric"><span>Promedio diario</span><strong>{money(total/Math.max(1,new Date().getDate()))}</strong><small>Para el período seleccionado</small></Card><Card className="metric"><span>Cuotas del mes</span><strong>{rows.filter(x=>x.is_installment).length}</strong><small>Sin duplicar la compra original</small></Card></div><div className="reports-grid"><Chart title="Gastos por categoría"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={byCat} dataKey="total" nameKey="name" outerRadius={100}>{byCat.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip formatter={money}/><Legend/></PieChart></ResponsiveContainer></Chart><Chart title="Por medio de pago"><ResponsiveContainer width="100%" height={280}><BarChart data={byMethod}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis hide/><Tooltip formatter={money}/><Bar dataKey="total" fill="#5658d4" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Chart><Chart title="Evolución de 6 meses" wide><ResponsiveContainer width="100%" height={280}><LineChart data={evolution}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip formatter={money}/><Line dataKey="total" stroke="#ef7b45" strokeWidth={3}/></LineChart></ResponsiveContainer></Chart></div></>}
function Chart({title,children,wide}){return <Card className={wide?'chart-card chart-wide':'chart-card'}><h2>{title}</h2>{children}</Card>}
