import { useEffect,useRef,useState } from 'react'
import { Download,LogOut,Moon,Sun,Trash2,Upload,UserRound } from 'lucide-react'
import { Button,Card,Field,PageHeader } from '../components/ui'
import { useAuth } from '../context/AuthContext'
import { useData } from '../context/DataContext'
import { useTheme } from '../context/ThemeContext'
import { supabase } from '../lib/supabase'
const validTables=['accounts','credit_cards','categories','transactions','installment_plans','installments','budgets','scheduled_payments','recurring_expenses','tags','transaction_tags']
export default function SettingsPage(){const{user,signOut}=useAuth(),data=useData(),{theme,toggle}=useTheme(),fileRef=useRef(),profile=data.profiles[0],[form,setForm]=useState({full_name:profile?.full_name||user?.user_metadata?.full_name||'',main_currency:profile?.main_currency||'ARS',timezone:profile?.timezone||'America/Argentina/Buenos_Aires',date_format:profile?.date_format||'dd/MM/yyyy',month_start_day:profile?.month_start_day||1,notifications_enabled:profile?.notifications_enabled??true}),[message,setMessage]=useState('')
 useEffect(()=>{if(profile?.id)setForm({full_name:profile.full_name||'',main_currency:profile.main_currency||'ARS',timezone:profile.timezone||'America/Argentina/Buenos_Aires',date_format:profile.date_format||'dd/MM/yyyy',month_start_day:profile.month_start_day||1,notifications_enabled:profile.notifications_enabled??true})},[profile])
 const exportJson=async()=>{const payload={app:'faro',version:1,exported_at:new Date().toISOString(),data:Object.fromEntries(validTables.map(t=>[t,data[t]]))};download('faro-respaldo.json',JSON.stringify(payload,null,2),'application/json')}
 const exportCsv=()=>{const columns=['purchase_date','description','merchant','amount','currency','payment_method','installment_count','notes'];const rows=[columns,...data.transactions.map(item=>columns.map(column=>item[column]??''))];download('faro-movimientos.csv',rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv;charset=utf-8')}
 const importJson=async e=>{try{const parsed=JSON.parse(await e.target.files[0].text());if(parsed.app!=='faro'||parsed.version!==1||!parsed.data||!validTables.every(t=>Array.isArray(parsed.data[t])))throw new Error('El archivo no tiene una estructura válida de Faro.');if(!confirm('La importación agregará o actualizará los registros del archivo. ¿Continuar?'))return;const{error}=await supabase.rpc('import_user_data',{p_payload:parsed.data});if(error)throw error;await data.refresh();setMessage('Respaldo importado correctamente.')}catch(err){setMessage(err.message)}finally{e.target.value=''}}
 const save=async e=>{e.preventDefault();let nextMessage='Configuración guardada.';if(form.notifications_enabled&&'Notification' in window&&Notification.permission==='default'){const permission=await Notification.requestPermission();if(permission!=='granted')nextMessage='Configuración guardada, pero el navegador no autorizó las notificaciones.'}await data.save('profiles',{id:user.id,...form});setMessage(nextMessage)}
 const deleteAccount=async()=>{if(prompt('Esta acción es irreversible. Escribí ELIMINAR para confirmar:')!=='ELIMINAR')return;const{error}=await supabase.rpc('delete_my_account');if(error)setMessage(error.message);else await signOut()}
 return <><PageHeader eyebrow="Preferencias" title="Configuración" description="Cuenta, formato, apariencia y respaldo de tus datos."/><div className="settings-grid"><Card><div className="section-title"><span><UserRound/></span><div><h2>Perfil y región</h2><p>Valores predeterminados para toda la aplicación.</p></div></div><form onSubmit={save}><div className="form-grid"><Field label="Nombre"><input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></Field><Field label="Moneda principal"><select value={form.main_currency} onChange={e=>setForm({...form,main_currency:e.target.value})}><option>ARS</option><option>USD</option></select></Field><Field label="Zona horaria"><input value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field><Field label="Formato de fecha"><select value={form.date_format} onChange={e=>setForm({...form,date_format:e.target.value})}><option value="dd/MM/yyyy">DD/MM/AAAA</option><option value="MM/dd/yyyy">MM/DD/AAAA</option></select></Field><Field label="Primer día del mes"><input type="number" min="1" max="28" value={form.month_start_day} onChange={e=>setForm({...form,month_start_day:Number(e.target.value)})}/></Field></div><label className="check-field"><input type="checkbox" checked={form.notifications_enabled} onChange={e=>setForm({...form,notifications_enabled:e.target.checked})}/>Activar recordatorios locales</label><Button>Guardar cambios</Button></form></Card><Card><h2>Apariencia y datos</h2><div className="settings-actions"><button onClick={toggle}>{theme==='light'?<Moon/>:<Sun/>}<span><strong>Tema {theme==='light'?'oscuro':'claro'}</strong><small>Cambiar apariencia</small></span></button><button onClick={exportJson}><Download/><span><strong>Exportar JSON</strong><small>Respaldo completo y portable</small></span></button><button onClick={exportCsv}><Download/><span><strong>Exportar CSV</strong><small>Todos los movimientos</small></span></button><button onClick={()=>fileRef.current.click()}><Upload/><span><strong>Importar respaldo</strong><small>Valida antes de guardar</small></span></button><input ref={fileRef} hidden type="file" accept="application/json" onChange={importJson}/><button onClick={signOut}><LogOut/><span><strong>Cerrar sesión</strong><small>Tu información queda guardada</small></span></button><button className="danger" onClick={deleteAccount}><Trash2/><span><strong>Eliminar cuenta</strong><small>Borra definitivamente todos tus datos</small></span></button></div>{message&&<p className="form-alert">{message}</p>}</Card></div></>}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
