import { useState } from 'react'
import { format } from 'date-fns'
import { ArrowLeft,CheckCircle2,CloudOff,ReceiptText } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button,Card,Field,PageHeader } from '../components/ui'
import { PAYMENT_METHODS,RECURRENCES } from '../constants/app'
import { useData } from '../context/DataContext'

const initial={description:'',amount:'',purchase_date:format(new Date(),'yyyy-MM-dd'),category_id:'',payment_method:'cash',credit_card_id:'',currency:'ARS',installment_count:1,current_installment:1,first_due_date:'',statement_period_override:'',merchant:'',notes:'',is_recurring:false,recurrence_frequency:'monthly',tags:'',fixed_installment_amount:''}

export default function TransactionFormPage(){
 const[form,setForm]=useState(initial),[error,setError]=useState(''),[saving,setSaving]=useState(false),[done,setDone]=useState(null)
 const data=useData(),navigate=useNavigate()
 const update=(key,value)=>setForm(current=>({...current,[key]:value}))
 const submit=async event=>{
  event.preventDefault();setError('')
  if(form.payment_method==='credit_card'&&!form.credit_card_id)return setError('Seleccioná la tarjeta utilizada.')
  if(form.payment_method==='credit_card'&&!form.first_due_date)return setError('Indicá el vencimiento estimado de esta compra.')
  setSaving(true)
  try{
   const payload={...form,id:crypto.randomUUID(),client_id:crypto.randomUUID(),amount:Number(form.amount),installment_count:Number(form.installment_count),current_installment:Number(form.current_installment),fixed_installment_amount:form.fixed_installment_amount?Number(form.fixed_installment_amount):null,credit_card_id:form.credit_card_id||null,category_id:form.category_id||null,tags:form.tags.split(',').map(item=>item.trim()).filter(Boolean)}
   const result=await data.addTransaction(payload);setDone(result.queued?'queued':'saved');setForm(initial)
  }catch(submitError){setError(submitError.message)}finally{setSaving(false)}
 }
 return <><PageHeader eyebrow="Nuevo movimiento" title="Registrar un consumo" description="Cargá los datos del gasto. Los vencimientos de tarjeta se definen en cada consumo." action={<Button variant="ghost" onClick={()=>navigate(-1)}><ArrowLeft/>Volver</Button>}/>
  {done&&<div className="form-alert success">{done==='queued'?<CloudOff/>:<CheckCircle2/>}{done==='queued'?'Guardado en este dispositivo. Se sincronizará al recuperar conexión.':'Consumo guardado correctamente.'}</div>}
  <form onSubmit={submit}><Card className="form-card"><div className="section-title"><span><ReceiptText/></span><div><h2>Datos del consumo</h2><p>Información principal del movimiento.</p></div></div><div className="form-grid"><Field label="Descripción *"><input required maxLength="120" value={form.description} onChange={event=>update('description',event.target.value)} placeholder="Ej. Compra semanal"/></Field><Field label="Importe *"><div className="input-prefix"><span>$</span><input type="number" min=".01" step=".01" required value={form.amount} onChange={event=>update('amount',event.target.value)} placeholder="0,00"/></div></Field><Field label="Fecha de compra *"><input type="date" required value={form.purchase_date} onChange={event=>update('purchase_date',event.target.value)}/></Field><Field label="Categoría"><select value={form.category_id} onChange={event=>update('category_id',event.target.value)}><option value="">Sin categoría</option>{data.categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Medio de pago *"><select value={form.payment_method} onChange={event=>update('payment_method',event.target.value)}>{PAYMENT_METHODS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Moneda"><select value={form.currency} onChange={event=>update('currency',event.target.value)}><option>ARS</option><option>USD</option></select></Field>{form.payment_method==='credit_card'&&<Field label="Tarjeta *"><select required value={form.credit_card_id} onChange={event=>update('credit_card_id',event.target.value)}><option value="">Seleccionar</option>{data.credit_cards.filter(card=>card.active).map(card=><option key={card.id} value={card.id}>{card.name} · {card.issuer}</option>)}</select></Field>}<Field label="Comercio"><input maxLength="120" value={form.merchant} onChange={event=>update('merchant',event.target.value)}/></Field></div></Card>
  {form.payment_method==='credit_card'&&<Card className="form-card"><div className="section-title"><span><ReceiptText/></span><div><h2>Cuotas y vencimiento</h2><p>La fecha se carga por compra porque puede cambiar en cada resumen.</p></div></div><div className="form-grid"><Field label={Number(form.installment_count)>1?'Primer vencimiento *':'Vencimiento estimado *'}><input type="date" required value={form.first_due_date} onChange={event=>update('first_due_date',event.target.value)}/></Field><Field label="Cantidad de cuotas"><input type="number" min="1" max="120" value={form.installment_count} onChange={event=>update('installment_count',event.target.value)}/></Field><Field label="Número de cuota actual"><input type="number" min="1" max={form.installment_count} value={form.current_installment} onChange={event=>update('current_installment',event.target.value)}/></Field><Field label="Mes del resumen" hint="Opcional. Si queda vacío se usa el mes del vencimiento."><input type="month" value={form.statement_period_override} onChange={event=>update('statement_period_override',event.target.value)}/></Field>{Number(form.installment_count)>1&&<Field label="Importe fijo por cuota" hint="Opcional. Si queda vacío se reparte el total."><input type="number" min=".01" step=".01" value={form.fixed_installment_amount} onChange={event=>update('fixed_installment_amount',event.target.value)}/></Field>}</div></Card>}
  <Card className="form-card"><div className="form-grid"><Field label="Etiquetas" hint="Separadas por coma"><input value={form.tags} onChange={event=>update('tags',event.target.value)} placeholder="trabajo, viaje"/></Field><Field label="Notas"><textarea rows="3" value={form.notes} onChange={event=>update('notes',event.target.value)}/></Field><label className="check-field"><input type="checkbox" checked={form.is_recurring} onChange={event=>update('is_recurring',event.target.checked)}/><span>Es un gasto recurrente</span></label>{form.is_recurring&&<Field label="Frecuencia"><select value={form.recurrence_frequency} onChange={event=>update('recurrence_frequency',event.target.value)}>{RECURRENCES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field>}</div>{error&&<p className="form-alert error">{error}</p>}<div className="form-actions"><Button variant="ghost" type="button" onClick={()=>navigate(-1)}>Cancelar</Button><Button loading={saving}>Guardar consumo</Button></div></Card></form>
 </>}
