import { addMonths,endOfMonth,format,getDate,setDate } from 'date-fns'
export function safeDay(yearMonthDate,day){return setDate(yearMonthDate,Math.min(Number(day),getDate(endOfMonth(yearMonthDate))))}
export function statementForPurchase(purchaseDate,closingDay,dueDay){const date=new Date(`${purchaseDate}T12:00:00`);const statementMonth=getDate(date)>Number(closingDay)?addMonths(date,1):date;const dueBase=Number(dueDay)<=Number(closingDay)?addMonths(statementMonth,1):statementMonth;return{statementPeriod:format(statementMonth,'yyyy-MM'),closingDate:format(safeDay(statementMonth,closingDay),'yyyy-MM-dd'),dueDate:format(safeDay(dueBase,dueDay),'yyyy-MM-dd')}}
export function splitInstallments(total,count){const cents=Math.round(Number(total)*100);const base=Math.floor(cents/count);return Array.from({length:count},(_,index)=>(base+(index===count-1?cents-base*count:0))/100)}
export function buildInstallments({total,count,firstDueDate,card,fixedAmount}){const amounts=fixedAmount?Array.from({length:count},()=>Number(fixedAmount)):splitInstallments(total,count);return amounts.map((amount,index)=>{const dueBase=addMonths(new Date(`${firstDueDate}T12:00:00`),index);return{number:index+1,amount,due_date:format(safeDay(dueBase,card?.due_day||getDate(dueBase)),'yyyy-MM-dd'),statement_period:format(dueBase,'yyyy-MM'),status:'pending'}})}
export function expensesForPeriod(data,period){
 const direct=data.transactions.filter(transaction=>Number(transaction.installment_count)===1&&(transaction.payment_method==='credit_card'?transaction.statement_period===period:transaction.purchase_date?.startsWith(period)))
 const installmentRows=data.installments.filter(installment=>installment.statement_period===period).map(installment=>{const plan=data.installment_plans.find(item=>item.id===installment.plan_id);const transaction=data.transactions.find(item=>item.id===plan?.transaction_id);return transaction?{...transaction,id:installment.id,amount:installment.amount,due_date:installment.due_date,payment_status:installment.status,is_installment:true,installment_number:installment.number}:null}).filter(Boolean)
 return [...direct,...installmentRows]
}
